[package]
name = "doc-printable"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
image = "0.25.8"
imageproc = "0.25.0"
printpdf = { version = "0.8.2", features = ["jpeg", "png"] }
tiff = "0.10.3"
